apiVersion: apps/v1
kind: Deployment
metadata:
  name: container2-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: container2
  template:
    metadata:
      labels:
        app: container2
    spec:
      containers:
      - name: container2
        image: us-central1-docker.pkg.dev/kubernetes-assignment-453414/kubernetes-repo/container2:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        volumeMounts:
        - name: pv-storage
          mountPath: /jeel_PV_dir
      volumes:
      - name: pv-storage
        persistentVolumeClaim:
          claimName: pv-claim
---
apiVersion: v1
kind: Service
metadata:
  name: container2-service
spec:
  type: ClusterIP
  ports:
  - port: 5000
    targetPort: 5000
  selector:
    app: container2